### ISSUE TITLE
I've used your code and made some optimizations

### ISSUE THREAD

**Issue by zekroTJA** [Xferno2/Good-Night-Sleep-Tight#1]
Hey,

I came across your plugin on bukkit.org and laoded it on my spigot server *(1.14.3)*.  

We've notices a nasty issue that the plugin fails to check if the player is capable of going to bed, so if you click on a bed when it is daytime or montsers are nearby, the percentage-number counts up (also over 100%).

So, I forked your project and tried to fix these issues but becuase I did not really worked a lot with spigot plugins before, it was easier to create a plugin on my own, which is strongly inspired by your code and fixes the issue. Also, it is not necessary to hurt the player to wake up. There is a `player.wakeup()` function available to do this *(at least in the later versions of the spigot API)*.

This plugin's source code is available [here](https://github.com/zekroTJA/SleepBetter). I've added a notice to my readme that the project is strongly inspired by you, if this is okay.

If you do not agree to my plugin, tell me and I will take it private ;)

**Comment by Xferno2** [comment]
Everything is good, feel free to use the code I don't mind. Thanks for the explanation on why the code was bugged. I wish you the best with your plugin!
